# Azure Synapse Analytics build pipeline

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '58a3cb06-91b3-4f09-82b8-882ec0a9c038'
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: './build-pipeline.ps1'
    arguments: '-subscriptionId $(subscriptionId) -workspaceName $(workspaceName) -pipelineName $(pipelineName) -artifactPath $(artifactPath)'
  displayName: 'Deploy Azure Synapse Pipeline'
